#include <iostream>
#include <stdexcept>				// 引入例外類別
using namespace std;


int main (void)
{
	int a = 0;
	try
	{
		if (a == 0) {
			throw exception(); 	// 使例外發生
		}
		int b = 10/a;
		cout << 10 << " / " << a << " = "  << b << endl;
	}
	catch (const exception& e)
	{
		cout << e.what() << endl;
	}

	return 0;
};